for:
    'repo-name': 'trello-board-id'
    rules:
    -
        verbs: [card]
        comment: true
    -
        verbs: [close, closes]
        move:
            to: 'close-list-id'
        comment: true
    -
        verbs: [fix, fixes]
        move:
            to: 'fix-list-id'
